### ISSUE TITLE
Магические величины

### ISSUE THREAD

**Issue by Morfey216** [kirillstepanchuk/keksatgram#3]
В коде не должно быть неопознанных значений. Например - что означают числа 15 и 200?
https://github.com/kirillstepanchuk/keksatgram/blob/5a36b9626855a33c9e2125dd10702678c391ca3c/js/main.js#L38
См. критерий Д19. В коде не используются «магические значения», под каждое из них заведена отдельная переменная, названная как константа

**Comment by kirillstepanchuk** [comment]
добавил константы
