### ISSUE TITLE
Именование

### ISSUE THREAD

**Issue by Morfey216** [kirillstepanchuk/keksatgram#4]
1. https://github.com/kirillstepanchuk/keksatgram/blob/5a36b9626855a33c9e2125dd10702678c391ca3c/js/main.js#L14
Смотри критерий Б6...
2. https://github.com/kirillstepanchuk/keksatgram/blob/5a36b9626855a33c9e2125dd10702678c391ca3c/js/main.js#L49
Смотри критерий Б5

**Comment by kirillstepanchuk** [comment]
поправил
