### ISSUE TITLE
Странная переменная

### ISSUE THREAD

**Issue by Morfey216** [kirillstepanchuk/keksatgram#6]
Что такое picture ? Не увидел ее объявления... 
https://github.com/kirillstepanchuk/keksatgram/blob/5a36b9626855a33c9e2125dd10702678c391ca3c/js/main.js#L53
И если вдруг скажешь, что это она, то я не поверю : https://github.com/kirillstepanchuk/keksatgram/blob/5a36b9626855a33c9e2125dd10702678c391ca3c/js/main.js#L61

**Comment by kirillstepanchuk** [comment]
исправил
