### ISSUE TITLE
Работа с шаблоном

### ISSUE THREAD

**Issue by Morfey216** [kirillstepanchuk/keksatgram#7]
Нет смысла хранить темплэйт:
https://github.com/kirillstepanchuk/keksatgram/blob/5a36b9626855a33c9e2125dd10702678c391ca3c/js/main.js#L52
тебе ведь нужна разметка, а не сам контейнер шаблона

Далее ты клонируешь контент шаблона:
https://github.com/kirillstepanchuk/keksatgram/blob/5a36b9626855a33c9e2125dd10702678c391ca3c/js/main.js#L61

в результате получаем такую картину: http://joxi.ru/J2b8PMVtVZ733r

**Comment by kirillstepanchuk** [comment]
Поправил

**Comment by Morfey216** [comment]
ОК, это поправил.
Теперь следующая проблема, и касается она уже логики работы. Возьмем код:
https://github.com/kirillstepanchuk/keksatgram/blob/606d24b0f5f95578c2c6e43cfb3796147dc24e59/js/main.js#L99-L111
В этом коде ты сохранил шаблон (строка 99) и в нём же ищешь отдельные элементы (строки 100-102).
Далее в цикле для этих элементов, которые, напоминаю, всё еще часть шаблона, ты указываешь актуальные данные (строки 106-108). И лишь ПОСЛЕ этого ты клонируешь разметку для нового изображения (строка 109).

Логика должна быть иная: в цикле клонируешь шаблон, затем уже в клонированной разметке выполняешь поиск элементов и установку правильных данных.
И да - в данном случае уже не обязательно заводить переменные вроде pictureImage, данные можно заменить напрямую

**Comment by kirillstepanchuk** [comment]
Исправил
