### ISSUE TITLE
Добавление комментариев

### ISSUE THREAD

**Issue by Morfey216** [kirillstepanchuk/keksatgram#8]
У меня ощущение, что вы плохо читаете ТЗ... В задании нигде не сказано, что нужно клонировать разметку
https://github.com/kirillstepanchuk/keksatgram/blob/5a36b9626855a33c9e2125dd10702678c391ca3c/js/main.js#L91

Для выполнения задания необходимо генерировать элементы самостоятельно
https://developer.mozilla.org/ru/docs/Web/API/Document/createElement

**Comment by kirillstepanchuk** [comment]
Исправил
